# Generated by Django 4.1.1 on 2022-09-29 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['ingredientName']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menuItemName']},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='MenuItemName',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='MenuItemPrice',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientInStock',
            field=models.FloatField(default=0, verbose_name='Amount in stock'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientName',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientPricePerUnit',
            field=models.FloatField(default=0, verbose_name='Price per unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientUnit',
            field=models.CharField(max_length=10, verbose_name='Unit of measurement'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='menuItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem', verbose_name='Menu Item'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient', verbose_name='Required Ingredient'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='menuItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem', verbose_name='Menu Item'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Required Amount'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menuItemName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='Menu Item Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menuItemPrice',
            field=models.FloatField(default=0, verbose_name='Menu Item Price'),
        ),
    ]
